php:
  build: ./
  environment:
    - |
      FRX_PHP_INI=
      date.timezone = "Europe/Paris"
      post_max_size = 10M
      upload_max_filesize = 10M
      log_errors = true
      error_log = /var/log/php.log
    - |
      FRX_APACHE_ENABLE_MOD=
      rewrite
    - FRX_APACHE_DOCUMENT_ROOT=/var/www/html/public
    - |
      FRX_SCRIPT_START=
      chown www-data:www-data -R .